; PlatformIO Project Configuration File

[platformio]
; Normal Upload button will use OTA.
; default_envs = esp32dev_ota
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

; Required for OTA firmware slots
board_build.partitions = default.csv

lib_deps =
    adafruit/Adafruit BNO08x @ ^1.2.5

; Wire is already included in the ESP32 Arduino framework.

build_flags =
    -D CORE_DEBUG_LEVEL=2

; USB upload environment
upload_protocol = esptool


[env:esp32dev_ota]
extends = env:esp32dev
upload_protocol = espota

; Keep only ONE upload_port uncommented.

; Hostname
; upload_port = imu-node-3.local

; Node 1
; upload_port = 192.168.8.187  

; Node 2
upload_port = 192.168.8.123

; Node 3
; upload_port = 192.168.8.104

; Node 4
; upload_port = 192.168.8.131

; Must match OTA_PORT and OTA_PASSWORD in ota_update.cpp
upload_flags =
    --port=3232
    --auth=Hirushan




